Harden the C primitives type against -Wcast-function-type
[GCC] and [clang] both have a `-Wcast-function-type` warning under
`-Wextra`, that complains about casts in our list of primitives. This
warning is also (sometimes?) enabled by clang-cl `-W4` option.

    runtime/prims.c:920:3: error: cast between incompatible function
    types from ‘value (*)(value)’ {aka ‘long int (*)(long int)’} to
    ‘value (*)(void)’ {aka ‘long int (*)(void)’}
    [-Werror=cast-function-type]
      920 |   (c_primitive) caml_zstd_initialize,
          |   ^

[GCC]: https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wcast-function-type
[clang]: https://clang.llvm.org/docs/DiagnosticsReference.html#wcast-function-type

I'm trying to silence this warning, but without disabling it globally
with `-Wno-cast-function-type`, as it could still catch problems.

1. GCC has a workaround that's unsupported by clang.

   > The function type `void (*) (void)` is special and matches
   >  everything, which can be used to suppress this warning.

   It's not ideal as it could be the prototype of an existing
   function.

2. We can instead store the function pointers as `void *`, a la
   `dlsym(3)`, in the primitive array. Recent POSIX guarantees that
   function pointers returned by `dlsym` may be stored in object
   pointers, but no longer that _any_ function pointer may be stored
   in an object pointer (see POSIX 2008 § 2.12.3 Pointer Types,
   removed in later versions).

   In practice, (I think) storing function pointers in object pointers
   should be fine on any modern, non-segmented architectures. This is
   also common practice on Windows.

3. Define a generic function pointer type that any function pointer
   can be cast to and from, but that is not callable. This allows
   using the `-Wcast-function-type` warning for catching possible
   future mistakes.

   - C⁠+⁠+26 has a proposal for a generic function pointer:
     [P2986R0 Generic Function Pointer](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2023/p2986r0.html)
   - There was one for C23, not retained at the time:
     [N2230 Generic Function Pointer](https://www.open-std.org/jtc1/sc22/wg14/www/docs/n2230.htm)

   We can use the work-around described in the draft, but without a
   compiler attribute, we have to resort to using compiler-specific
   pragmas to disable the `-Wcast-function-type` warning around casts
   to `caml_function_ptr_t`. Using the pragmas is arguably tedious. I
   assume that all compilers that have this warning also have ways of
   disabling it locally.

Here, I'm going with option 3, inspired by the N2230 draft, using
compiler pragmas.